// Multiplatform fixture-test base. Mirrors the JVM-only DocxFixtureTest
// shape but uses kotlin.test, our hand-rolled XmlDiff, and the
// expect/actual fixture loader so the same battery runs on jvmTest +
// macosArm64Test + iosSimulatorArm64Test.
package io.docxkt.testing

import io.docxkt.api.Document
import io.docxkt.api.toByteArray
import io.docxkt.pack.ZipReader
import kotlin.test.Test
import kotlin.test.fail

/**
 * Base class for fixture-backed tests that run on every target.
 *
 * Subclass with [fixtureName] (folder under
 * `core/src/jvmTest/resources/fixtures/`) and implement [build] to
 * construct the document via the DSL. By default [comparedParts]
 * defaults to every `.xml` / `.rels` file present in the fixture
 * folder MINUS the keys in [defaultDivergences] and
 * [expectedDivergences]. Override [comparedParts] explicitly when a
 * narrower scope is needed.
 *
 * The fixture-folder walk happens at Gradle configuration time —
 * `FIXTURE_CATALOG` is generated by `core/build.gradle.kts` and
 * embedded into the `commonTest` source set, so auto-discovery works
 * on every target without a runtime filesystem walk.
 */
internal abstract class DocxFixtureTest(
    private val fixtureName: String,
) {
    protected abstract fun build(): Document

    /**
     * Explicit list of XML parts to diff against the fixture. Empty
     * list (the default) triggers auto-discovery via [FIXTURE_CATALOG]
     * minus the divergence keys.
     */
    protected open val comparedParts: List<String> = emptyList()

    /**
     * Per-test rationale for parts allowed to diverge. Merged with
     * [defaultDivergences] before auto-discovery filtering.
     */
    protected open val expectedDivergences: Map<String, String> = emptyMap()

    /** Binary parts (images, fonts) compared via byte equality. */
    protected open val comparedBinaryParts: List<String> = emptyList()

    @Test
    fun `matches golden fixture`() {
        val actualBytes = build().toByteArray()
        val actualEntries = ZipReader.read(actualBytes)

        val divergences = defaultDivergences + expectedDivergences
        val effectiveParts = if (comparedParts.isNotEmpty()) {
            comparedParts
        } else {
            (FIXTURE_CATALOG[fixtureName] ?: emptyList()).filter { it !in divergences }
        }

        if (effectiveParts.isEmpty() && comparedBinaryParts.isEmpty()) {
            fail("$fixtureName: nothing to compare (no parts in catalog and no overrides)")
        }

        val failures = mutableListOf<String>()

        for (part in effectiveParts) {
            val actualXml = actualEntries[part]?.decodeToString()
                ?: run {
                    failures += "$part — generated .docx is missing this part"
                    continue
                }
            val expectedXml = loadFixtureXml(fixtureName, part)
            val diff = XmlDiff.diff(expectedXml, actualXml)
            if (diff != null) {
                failures += "$part — $diff"
            }
        }

        for (part in comparedBinaryParts) {
            val actualBin = actualEntries[part]
                ?: run {
                    failures += "$part — generated .docx is missing this binary part"
                    continue
                }
            val expectedBin = loadFixtureBytes(fixtureName, part)
            if (!actualBin.contentEquals(expectedBin)) {
                failures += "$part — binary bytes differ (${actualBin.size} vs ${expectedBin.size})"
            }
        }

        if (failures.isNotEmpty()) {
            fail(
                "$fixtureName: ${failures.size}/${effectiveParts.size + comparedBinaryParts.size} part(s) diverged:\n" +
                    failures.joinToString("\n") { "  - $it" },
            )
        }
    }

    internal companion object {
        /**
         * "Minimum-part output" rationale — same set as the legacy
         * JVM `DocxFixtureTest.defaultDivergences`. The DSL emits a
         * part only when it has user-supplied content; upstream
         * always ships these even when empty.
         */
        val defaultDivergences: Map<String, String> = mapOf(
            "[Content_Types].xml" to
                "derived from which parts/content the doc has — minimum-part design.",
            "_rels/.rels" to
                "derived from which package-level rels exist — minimum-part design.",
            "word/_rels/document.xml.rels" to
                "derived from which document-level rels exist — minimum-part design.",
            "docProps/core.xml" to
                "dcterms:created / dcterms:modified default to nowIso8601(); fixture has sentinel.",
            "docProps/custom.xml" to
                "ours: emit only when DSL registers customProperties.",
            "word/comments.xml" to
                "ours: emit only when DSL registers comments.",
            "word/endnotes.xml" to
                "ours: emit only when DSL registers endnotes.",
            "word/footnotes.xml" to
                "ours: emit only when DSL registers footnotes.",
            "word/numbering.xml" to
                "ours: emit only when DSL registers list templates.",
            "word/styles.xml" to
                "ours: emit only when DSL registers styles.",
            "word/_rels/comments.xml.rels" to
                "ours: emitted with comments.xml only.",
            "word/_rels/endnotes.xml.rels" to
                "ours: emitted with endnotes.xml only.",
            "word/_rels/footnotes.xml.rels" to
                "ours: emitted with footnotes.xml only.",
            "word/_rels/fontTable.xml.rels" to
                "ours: fontTable rels emitted only when fonts are embedded.",
        ) + (1..6).associate { n ->
            "word/_rels/header$n.xml.rels" to
                "ours: header$n rels emitted only when header content has rIds (image/hyperlink/etc.)."
        } + (1..6).associate { n ->
            "word/_rels/footer$n.xml.rels" to
                "ours: footer$n rels emitted only when footer content has rIds (image/hyperlink/etc.)."
        }
    }
}
