// Multiplatform fixture-bytes loader for the commonTest port of the
// fixture battery. Each target supplies an `actual` that resolves a
// `(fixtureName, partPath)` pair to the bytes of the on-disk file
// generated by upstream dolanmiu/docx.
//
// JVM uses classpath via getResourceAsStream — fixtures live at
// `core/src/jvmTest/resources/fixtures/` and are auto-copied onto the
// jvmTest classpath by KGP.
//
// Native targets (macosArm64, iosSimulatorArm64, …) read the fixture
// from the project filesystem at the path supplied by the
// `DOCXKT_FIXTURES_ROOT` environment variable. Gradle wires this
// variable on each Native test task — see `core/build.gradle.kts`.
package io.docxkt.testing

internal expect fun loadFixtureBytes(fixtureName: String, partPath: String): ByteArray

internal fun loadFixtureXml(fixtureName: String, partPath: String): String =
    loadFixtureBytes(fixtureName, partPath).decodeToString()
